import type { CardDef } from "../ritual/types.ts";

/** Phase 1 Rider-Waite structure T10.3 — meanings live in spec; ids drive ritual state. */
export const RIDER_WAITE_CARDS: readonly CardDef[] = [
  { id: "fool", name: "0 The Fool", arcana: "major" },
  { id: "magician", name: "I The Magician", arcana: "major" },
  { id: "high-priestess", name: "II The High Priestess", arcana: "major" },
  { id: "empress", name: "III The Empress", arcana: "major" },
  { id: "emperor", name: "IV The Emperor", arcana: "major" },
  { id: "hierophant", name: "V The Hierophant", arcana: "major" },
  { id: "lovers", name: "VI The Lovers", arcana: "major" },
  { id: "chariot", name: "VII The Chariot", arcana: "major" },
  { id: "strength", name: "VIII Strength", arcana: "major" },
  { id: "hermit", name: "IX The Hermit", arcana: "major" },
  { id: "wheel", name: "X Wheel of Fortune", arcana: "major" },
  { id: "justice", name: "XI Justice", arcana: "major" },
  { id: "hanged-one", name: "XII The Hanged One", arcana: "major" },
  { id: "death", name: "XIII Death", arcana: "major" },
  { id: "temperance", name: "XIV Temperance", arcana: "major" },
  { id: "devil", name: "XV The Devil", arcana: "major" },
  { id: "tower", name: "XVI The Tower", arcana: "major" },
  { id: "star", name: "XVII The Star", arcana: "major" },
  { id: "moon", name: "XVIII The Moon", arcana: "major" },
  { id: "sun", name: "XIX The Sun", arcana: "major" },
  { id: "judgement", name: "XX Judgement", arcana: "major" },
  { id: "world", name: "XXI The World", arcana: "major" },
  { id: "ace-of-wands", name: "Ace of Wands", arcana: "minor", suit: "wands" },
  { id: "two-of-wands", name: "Two of Wands", arcana: "minor", suit: "wands" },
  { id: "three-of-wands", name: "Three of Wands", arcana: "minor", suit: "wands" },
  { id: "four-of-wands", name: "Four of Wands", arcana: "minor", suit: "wands" },
  { id: "five-of-wands", name: "Five of Wands", arcana: "minor", suit: "wands" },
  { id: "six-of-wands", name: "Six of Wands", arcana: "minor", suit: "wands" },
  { id: "seven-of-wands", name: "Seven of Wands", arcana: "minor", suit: "wands" },
  { id: "eight-of-wands", name: "Eight of Wands", arcana: "minor", suit: "wands" },
  { id: "nine-of-wands", name: "Nine of Wands", arcana: "minor", suit: "wands" },
  { id: "ten-of-wands", name: "Ten of Wands", arcana: "minor", suit: "wands" },
  { id: "page-of-wands", name: "Page of Wands", arcana: "minor", suit: "wands" },
  { id: "knight-of-wands", name: "Knight of Wands", arcana: "minor", suit: "wands" },
  { id: "queen-of-wands", name: "Queen of Wands", arcana: "minor", suit: "wands" },
  { id: "king-of-wands", name: "King of Wands", arcana: "minor", suit: "wands" },
  { id: "ace-of-cups", name: "Ace of Cups", arcana: "minor", suit: "cups" },
  { id: "two-of-cups", name: "Two of Cups", arcana: "minor", suit: "cups" },
  { id: "three-of-cups", name: "Three of Cups", arcana: "minor", suit: "cups" },
  { id: "four-of-cups", name: "Four of Cups", arcana: "minor", suit: "cups" },
  { id: "five-of-cups", name: "Five of Cups", arcana: "minor", suit: "cups" },
  { id: "six-of-cups", name: "Six of Cups", arcana: "minor", suit: "cups" },
  { id: "seven-of-cups", name: "Seven of Cups", arcana: "minor", suit: "cups" },
  { id: "eight-of-cups", name: "Eight of Cups", arcana: "minor", suit: "cups" },
  { id: "nine-of-cups", name: "Nine of Cups", arcana: "minor", suit: "cups" },
  { id: "ten-of-cups", name: "Ten of Cups", arcana: "minor", suit: "cups" },
  { id: "page-of-cups", name: "Page of Cups", arcana: "minor", suit: "cups" },
  { id: "knight-of-cups", name: "Knight of Cups", arcana: "minor", suit: "cups" },
  { id: "queen-of-cups", name: "Queen of Cups", arcana: "minor", suit: "cups" },
  { id: "king-of-cups", name: "King of Cups", arcana: "minor", suit: "cups" },
  { id: "ace-of-swords", name: "Ace of Swords", arcana: "minor", suit: "swords" },
  { id: "two-of-swords", name: "Two of Swords", arcana: "minor", suit: "swords" },
  { id: "three-of-swords", name: "Three of Swords", arcana: "minor", suit: "swords" },
  { id: "four-of-swords", name: "Four of Swords", arcana: "minor", suit: "swords" },
  { id: "five-of-swords", name: "Five of Swords", arcana: "minor", suit: "swords" },
  { id: "six-of-swords", name: "Six of Swords", arcana: "minor", suit: "swords" },
  { id: "seven-of-swords", name: "Seven of Swords", arcana: "minor", suit: "swords" },
  { id: "eight-of-swords", name: "Eight of Swords", arcana: "minor", suit: "swords" },
  { id: "nine-of-swords", name: "Nine of Swords", arcana: "minor", suit: "swords" },
  { id: "ten-of-swords", name: "Ten of Swords", arcana: "minor", suit: "swords" },
  { id: "page-of-swords", name: "Page of Swords", arcana: "minor", suit: "swords" },
  { id: "knight-of-swords", name: "Knight of Swords", arcana: "minor", suit: "swords" },
  { id: "queen-of-swords", name: "Queen of Swords", arcana: "minor", suit: "swords" },
  { id: "king-of-swords", name: "King of Swords", arcana: "minor", suit: "swords" },
  { id: "ace-of-pentacles", name: "Ace of Pentacles", arcana: "minor", suit: "pentacles" },
  { id: "two-of-pentacles", name: "Two of Pentacles", arcana: "minor", suit: "pentacles" },
  { id: "three-of-pentacles", name: "Three of Pentacles", arcana: "minor", suit: "pentacles" },
  { id: "four-of-pentacles", name: "Four of Pentacles", arcana: "minor", suit: "pentacles" },
  { id: "five-of-pentacles", name: "Five of Pentacles", arcana: "minor", suit: "pentacles" },
  { id: "six-of-pentacles", name: "Six of Pentacles", arcana: "minor", suit: "pentacles" },
  { id: "seven-of-pentacles", name: "Seven of Pentacles", arcana: "minor", suit: "pentacles" },
  { id: "eight-of-pentacles", name: "Eight of Pentacles", arcana: "minor", suit: "pentacles" },
  { id: "nine-of-pentacles", name: "Nine of Pentacles", arcana: "minor", suit: "pentacles" },
  { id: "ten-of-pentacles", name: "Ten of Pentacles", arcana: "minor", suit: "pentacles" },
  { id: "page-of-pentacles", name: "Page of Pentacles", arcana: "minor", suit: "pentacles" },
  { id: "knight-of-pentacles", name: "Knight of Pentacles", arcana: "minor", suit: "pentacles" },
  { id: "queen-of-pentacles", name: "Queen of Pentacles", arcana: "minor", suit: "pentacles" },
  { id: "king-of-pentacles", name: "King of Pentacles", arcana: "minor", suit: "pentacles" },
];

export const RIDER_WAITE_DECK_ID = "rider-waite" as const;
